apiVersion: v1
kind: Service
metadata:
  name: happybirthday-service
spec:
  selector:
    app: happybirthday
    version: "DEPLOYMENTVERSION"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000