name: Master Pipline
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest test.py

    - name: Build the Docker image and Push to DockerHub
      run: |
        DEPLOYMENTVERSION=$(date +%s)

        ::set-env name=DEPLOYMENTVERSION::$DEPLOYMENTVERSION

        docker build . --file Dockerfile --tag happybirthday:$DEPLOYMENTVERSION
        docker login --username=$DOCKERHUB_USERNAME --password=$DOCKERHUB_PASSWORD
        docker tag happybirthday:$DEPLOYMENTVERSION $DOCKERHUB_USERNAME/happybirthday:$DEPLOYMENTVERSION
        docker push $DOCKERHUB_USERNAME/happybirthday:$DEPLOYMENTVERSION
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASS }}
    - uses: actions/aws@master
    - name: Deploy to AWS Kubernetes Cluster
      run: |
        aws eks update-kubeconfig --name $EKS_Cluster_Name --region $AWS_DEFAULT_REGION
        DEPLOYMENT_FILE=deployment.yaml
        SERVICE_FILE=service.yaml
        DEPLOYMENTNAME=happybirthday-$DEPLOYMENTVERSION
        IMAGENAME=happybirthday
        IMAGEREPO=$DOCKERHUB_USERNAME
        
        sed -i "s/DEPLOYMENTNAME/${DEPLOYMENTNAME}/g" $DEPLOYMENT_FILE
        sed -i "s/DEPLOYMENTVERSION/${DEPLOYMENTVERSION}/g" $DEPLOYMENT_FILE
        sed -i "s/IMAGENAME/${IMAGENAME}/g; s/IMAGEREPO/${IMAGEREPO}/g" $DEPLOYMENT_FILE
        
        
        kubectl apply -f $DEPLOYMENT_FILE

        # Wait until the Deployment is ready by checking the MinimumReplicasAvailable condition.
        READY=$(kubectl get deploy $DEPLOYMENTNAME -o json | jq '.status.conditions[] | select(.reason == "MinimumReplicasAvailable") | .status' | tr -d '"')
        while [[ "$READY" != "True" ]]; do
            READY=$(kubectl get deploy $DEPLOYMENTNAME -o json | jq '.status.conditions[] | select(.reason == "MinimumReplicasAvailable") | .status' | tr -d '"')
            sleep 5
        done

        # Update the service selector with the new version
        sed -i "s/DEPLOYMENTVERSION/${DEPLOYMENTVERSION}/g" $SERVICE_FILE
        kubectl apply -f $SERVICE_FILE
        echo "Done."
      env:
        AWS_DEFAULT_REGION: eu-central-1
        AWS_Access_Key_ID: ${{ secrets.AWS_Access_Key_ID }}
        AWS_Secret_Access_Key: ${{ secrets.AWS_Secret_Access_Key }}
        EKS_Cluster_Name: ${{ secrets.AWS_Secret_Access_Key }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: ~/.kube