name: Master Pipline
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest test.py

    - name: Build the Docker image and Push to DockerHub
      run: |
        TAG=$(date +%s)
        docker build . --file Dockerfile --tag happybirthday:$TAG
        docker login --username=highelf --email=amir.modiri.master@gmail.com --password=hNfRcb3PvcSNkub
        docker tag happybirthday:$TAG highelf/happybirthday:$TAG
        docker push highelf/happybirthday:$TAG