name: Build Image and Push to DockerHub

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag highelf/happybirthday:$(date +%s)
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.4
      with:
        repo_name: highelf/happybirthday
        username: highelf
        password: hNfRcb3PvcSNkub