name: Python Test
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag happybirthday:$(date +%s)
    - name: Tag Buil Publish Docker
      uses: AhnSeongHyun/action-tag-docker-build-push@v1.0.0
        with:
          repo_name: highelf/happybirthday
          username: highelf
          password: hNfRcb3PvcSNkub